import UrlScanModel from "../models/urlScanModel.js";
import ScanModel from "../models/scanModel.js";
import ApiError from "../utils/ApiError.js";

class UrlScanService {
  /**create url scan result
   * this method stores the result generated by the URL scanner.
   * URL analysis itself should be handled by urlScanner/scanEngine.
   */
  static async createUrlScan(scanId, data) {
    if (!scanId) {
      throw new ApiError(400, "Scan ID is required.");
    }
    if (!data) {
      throw new ApiError(400, "URL scan data is required.");
    }

    // Check for parent scan from scans table
    const scan = await ScanModel.findById(scanId);
    if (!scan) {
      throw new ApiError(404, "Scan not found.");
    }
    //check if the scan type is URL
    if (scan.scan_type !== "URL") {
      throw new ApiError(400, "The specified scan is not a URL scan.");
    }
    // Only allow URL scan result while scan status is processing
    if (scan.status !== "PROCESSING") {
      throw new ApiError(
        400,
        `URL scan result cannot be created when scan status is ${scan.status}.`,
      );
    }
    //check if the url scan result already exists for this scan
    const existingScan = await UrlScanModel.findByScanId(scanId);
    if (existingScan) {
      throw new ApiError(409, "URL scan result already exists for this scan.");
    }
    const { input_url, normalized_url, domain_name } = data;
    if (!input_url) {
      throw new ApiError(400, "Input URL is required.");
    }
    if (!normalized_url) {
      throw new ApiError(400, "Normalized URL is required.");
    }
    if (!domain_name) {
      throw new ApiError(400, "Domain name is required.");
    }
    const urlScan = await UrlScanModel.create({
      scan_id: scanId,
      input_url,
      normalized_url,
      final_url: data.final_url || null,
      domain_name,
      protocol: data.protocol || null,
      uses_https: data.uses_https || null,
      url_length: data.url_length || null,
      hostname_length: data.hostname_length || null,
      path_length: data.path_length || null,
      query_length: data.query_length || null,
      subdomain_count: data.subdomain_count || null,
      contains_ip: data.contains_ip || null,
      contains_shortener: data.contains_shortener || null,
      contains_at_symbol: data.contains_at_symbol || null,
      contains_hex_encoding: data.contains_hex_encoding || null,
      contains_punycode: data.contains_punycode || null,
      contains_suspicious_tld: data.contains_suspicious_tld || null,
      has_non_standard_port: data.has_non_standard_port || null,
      domain_backlisted: data.domain_backlisted || null,
      url_backlisted: data.url_backlisted || null,
      reputation_score: data.reputation_score || null,
      google_safe: data.google_safe || null,
      virustotal_safe: data.virustotal_safe || null,
      recommendation: data.recommendation || null,
      api_response: data.api_response || null,
    });
    return urlScan;
  }
  /** get url scan result by ID */
  static async getUrlScanById(id, userId) {
    if (!id) {
      throw new ApiError(400, "URL scan ID is required.");
    }

    const urlScan = await UrlScanModel.findById(id);

    if (!urlScan) {
      throw new ApiError(404, "URL scan not found.");
    }

    // Check parent scan for ownership
    const scan = await ScanModel.findById(urlScan.scan_id);

    if (!scan) {
      throw new ApiError(404, "Parent scan not found.");
    }

    if (userId && scan.user_id !== userId) {
      throw new ApiError(
        403,
        "You are not authorized to access this URL scan.",
      );
    }

    return urlScan;
  }

  /**get url scan by its parent scan ID */

  static async getByParentScanId(scanId, userId) {
    if (!scanId) {
      throw new ApiError(400, "Scan ID is required.");
    }

    const scan = await ScanModel.findById(scanId);

    if (!scan) {
      throw new ApiError(404, "Scan not found.");
    }

    if (scan.scan_type !== "URL") {
      throw new ApiError(400, "The specified scan is not a URL scan.");
    }

    if (userId && scan.user_id !== userId) {
      throw new ApiError(
        403,
        "You are not authorized to access this URL scan.",
      );
    }

    const urlScan = await UrlScanModel.findByScanId(scanId);

    if (!urlScan) {
      throw new ApiError(404, "URL scan result not found.");
    }

    return urlScan;
  }
  /**find url scan by a domain name for specific user */
  static async getByDomainNameAndUser(domainName, userId) {
    if (!domainName) {
      throw new ApiError(400, "Domain name is required.");
    }

    const urlScans = await UrlScanModel.findByDomainNameAndUser(
      domainName,
      userId,
    );

    if (urlScans.length === 0) {
      throw new ApiError(
        404,
        "URL scan result not found for the specified domain.",
      );
    }
    /** now no need to check ownership as we getting the url_scans
     * for a particular domain name for particular user
     */

    // Check ownership
    // const scan = await ScanModel.findById(urlScan.scan_id);
    // if (!scan) {
    //   throw new ApiError(404, "Parent scan not found.");
    // }
    // if (userId && scan.user_id !== userId) {
    //   throw new ApiError(
    //     403,
    //     "You are not authorized to access this URL scan.",
    //   );
    // }

    return urlScans;
  }
  /**
   * Get recent scans for a domain
   */
  static async getByDomain(domainName) {
    if (!domainName) {
      throw new ApiError(400, "Domain name is required.");
    }

    return await UrlScanModel.findByDomain(domainName);
  }
  /**
   * Update URL scan result
   *
   * Mainly useful when additional analysis becomes available,
   * such as Google Safe Browsing, VirusTotal, AI analysis, etc.
   */
  static async updateUrlScan(id, data, userId) {
    if (!id) {
      throw new ApiError(400, "URL scan Id is required.");
    }
    if (!data || Object.keys(data).length === 0) {
      throw new ApiError(400, "At least one field is required for update.");
    }
    const existingScan = await UrlScanModel.findById(id);
    if (!existingScan) {
      throw new ApiError(404, "URL scan not found");
    }
    //check for parent scan id
    const scan = await ScanModel.findById(existingScan.scan_id);
    if (!scan) {
      throw new ApiError(404, "Parent scan not found.");
    }
    if (userId && scan.user_id !== userId) {
      throw new ApiError(403, "You are not authorised to update this URL scan");
    }
    /**allow no change in URL scan if
     * parent scan has status COMPLETED
     */
    if (scan.status === "COMPLETED") {
      throw new ApiError(400, "Completed URL scan results cannot be modified.");
    }
    const updatedScan = await UrlScanModel.update(id, data);
    return updatedScan;
  }
  /**DELETE URL scan result */
  static async deleteUrlScan(id, userId) {
    if (!id) {
      throw new ApiError(400, "URL scan Id is required.");
    }
    const existingScan = await UrlScanModel.findById(id);
    if (!existingScan) {
      throw new ApiError(404, "URL scan not found");
    }
    //check for parent scan id
    const scan = await ScanModel.findById(existingScan.scan_id);
    if (!scan) {
      throw new ApiError(404, "Parent scan not found.");
    }
    if (userId && scan.user_id !== userId) {
      throw new ApiError(403, "You are not authorised to delete this URL scan");
    }
    /**delete not allowed if
     * parent scan has status PROCESSING
     */
    if (scan.status === "PROCESSING") {
      throw new ApiError(
        400,
        "A URL scan currently being processed cannot be deleted.",
      );
    }
    const deletedScan = await UrlScanModel.delete(id);
    if (!deletedScan) {
      throw new ApiError(404, "URL scan not found.");
    }
    return deletedScan;
  }
  /**Get number of scans performed for a domain */
  static async countByDomain(domainName) {
    if (!domainName) {
      throw new ApiError(400, "Domain name is required.");
    }
    return await UrlScanModel.countByDomain(domainName);
  }
}

export default UrlScanService;
